name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test
      - name: update report file
        run: |
          coverage=$(jq '.total[].pct' < ./coverage/coverage-summary.json | awk '{s+=$1} END {print (s/4)}')
          tmp=$(mktemp)
          jq ".testCoverage = ${coverage}" report.json > "$tmp" && mv "$tmp" report.json
      - name: commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'andriyorehov@gmail.com'
          git add .
          git commit -am "Automated report"
          git push
